// <auto-generated />
namespace SimpleAudit.Web.MyDbContextMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class idGeneratedByCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idGeneratedByCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201505090324442_idGeneratedByCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
